FROM onlyoffice/documentserver
RUN sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/app.js && \
     sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/mobile/app.js && \
     sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/mobile/app.js && \
     sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/presentationeditor/mobile/app.js && \
     sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/app.js && \
     sed -i 's/this\._state\.licenseType=e/this\._state\.licenseType=0/g' /var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/mobile/app.js

