FROM ghost
#COPY ./config.js /var/lib/ghost/config.js
#COPY ./config.production.json /var/lib/ghost/config.production.json


WORKDIR /var/lib/ghost/versions/3.13.3/
ENTRYPOINT:

EXPOSE 2368
CMD ["npm","start","--production"]